# Note: MIDI access is not auto-connected. Run:
# - sudo snap connect powertabeditor:alsa
# - sudo snap connect powertabeditor:jack1

name: powertabeditor
base: core22
version: '2.0.22'
adopt-info: powertabeditor

grade: stable
confinement: strict

parts:
  powertabeditor:
    parse-info: [usr/local/share/metainfo/powertabeditor.metainfo.xml]
    plugin: cmake
    source: https://github.com/powertab/powertabeditor.git
    source-tag: 2.0.22
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
      - -DPTE_BUILD_SNAP=ON
    build-snaps:
      - kde-qt6-core22-sdk # For Qt
    build-packages:
      - libasound2-dev
      - libboost-date-time-dev
      - libboost-dev
      - libboost-iostreams-dev
      - libminizip-dev
      - libpugixml-dev
      - librtmidi-dev
      - nlohmann-json3-dev
    stage-packages:
      - cups
      - libboost-date-time1.74.0
      - libboost-iostreams1.74.0
      - libasound2
      - libjack0
      - librtmidi6
      - libminizip1
      - libpugixml1v5
    override-prime: |
      craftctl default
      # Fix application icon path
      sed --in-place 's|^Icon=.*|Icon=\${SNAP}/usr/local/share/icons/hicolor/128x128/apps/powertabeditor.png|' usr/local/share/applications/powertabeditor.desktop

layout:
  # Bindings needed for ALSA, see https://forum.snapcraft.io/t/the-alsa-interface/7766/7
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/alsa:
    bind: $SNAP/etc/alsa
  # For the tuning dictionary (tunings.json)
  /usr/local/share:
    bind: $SNAP/usr/local/share

apps:
  powertabeditor:
    common-id: powertabeditor.desktop
    command: usr/local/bin/powertabeditor
    extensions:
      - kde-neon-6
    plugs:
      - alsa # For rtmidi's ALSA backend
      - audio-playback
      - home
      - network
      - jack1 # For rtmidi's JACK backend
